### ISSUE TITLE
Missing Course

### ISSUE THREAD

**Issue by zawie** [rice-apps/ultrascheduler-full#13]
@TheWillMundy I noticed a course was missing from hatch. Math 220 is offered next fall (and shows up in courses.rice.edu), but it doesn't show up in hatch.
<img width="1671" alt="Screen Shot 2020-07-15 at 3 46 08 PM" src="https://user-images.githubusercontent.com/15623191/87607659-b4eb0180-c6b2-11ea-8200-f005145649f5.png">

**Comment by TheWillMundy** [comment]
Hey Adam, great catch! We've known about some missing courses for a bit, and the `develop` branch actually resolves this issue by automatically syncing the courses daily (I checked and this course is included on that branch / database). Nonetheless, please do continue to let us know if there are any discrepancies so that we can check!

![image](https://user-images.githubusercontent.com/2747462/87896003-00840f00-ca15-11ea-9055-ae80122022bb.png)
